### ISSUE TITLE
CSS hides blog content without JS

### ISSUE THREAD

**Issue by dirkf** [IanNorris/PersonalWebsite#1]
https://github.com/IanNorris/PersonalWebsite/blob/master/web_root/assets/css/main.css#L75

If you delete this the result is an actual (interesting) web page that can be read as  served, so it might as well be visible without disabling styles.

If the content hiding is important for the JS, perhaps because it conceals the rehydration of the page, it could hide the element as its first step, or maybe animate the transition from the static HTML. Eg, leaving the linked CSS as-is, serve `<main class="js-reveal static-reveal">` in the static HTML and put `document.querySelectorAll("main.static-reveal").forEach(y=>y.removeAttribute("class"))` (I guess the jQuery equivalent won't be loaded yet) in some script run in the page JS soon after the `<main>` element is available should restore the current appearance on initial load and then the site code will re-enable `js-reveal` to display the JS page.

>I do not believe GPT-3 is currently capable of being used in most production settings where end-users can enter unconstrained text.

The set-up we had for computerised questionnaires in the Eliza era, a keyboard overlay with buttons over the Y and N keys, could help, if only it could be delivered to phones across the world!

**Comment by IanNorris** [comment]
Thanks for flagging this! I've confirmed the site now loads without JS.
